import 'dart:io';
import 'package:flutter/material.dart';

class StoryImage extends StatelessWidget {
  final String imageId;
  final VoidCallback? onTap;
  
  const StoryImage({super.key, required this.imageId, this.onTap});
  
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: SizedBox(
        height: 200,
        width: double.infinity,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(12),
            child: _buildImageContent(),
          ),
        ),
      ),
    );
  }
  
  Widget _buildImageContent() {
    // Check if imageId is a file path
    if (imageId.contains('/')) {
      final file = File(imageId);
      
      // Only try to display the file if it exists
      if (file.existsSync()) {
        return Stack(
          fit: StackFit.expand,
          children: [
            // Display the actual image
            Image.file(
              file,
              fit: BoxFit.cover,
            ),
            
            // Overlay gradient for better text visibility
            Positioned(
              bottom: 0,
              left: 0,
              right: 0,
              child: Container(
                padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.bottomCenter,
                    end: Alignment.topCenter,
                    colors: [
                      Colors.black.withOpacity(0.7),
                      Colors.transparent,
                    ],
                  ),
                ),
                child: const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      "Generated by Imagen",
                      style: TextStyle(
                        color: Colors.white70,
                        fontSize: 12,
                      ),
                    ),
                    SizedBox(width: 4),
                    Icon(
                      Icons.zoom_in,
                      color: Colors.white70,
                      size: 14,
                    ),
                  ],
                ),
              ),
            ),
          ],
        );
      }
    }
    
    // Fallback for non-file paths or non-existent files
    return Container(
      color: Colors.black26,
      alignment: Alignment.center,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(
            Icons.image,
            size: 48,
            color: Colors.white54,
          ),
          const SizedBox(height: 8),
          Text(
            imageId.contains('/') ? "Image not found" : imageId,
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          const Text(
            "Generated using Imagen",
            style: TextStyle(
              color: Colors.white70,
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }
}